use anyhow::{Context, bail};
use std::fs::{File, create_dir_all};
use std::io::Write;
use std::path::Path;
use tracing::{debug, info, instrument};

use crate::io::ConfigFile;

const CONFIG_EXPLANATION: &str = "# Generated by hyprshell, edit with `hyprshell config edit`\n";

/// needs a mutable ref because writing the config to file forces a sync of the struct values
/// into the backing toml edit Document which requires mutable ref
#[instrument(skip(config, config_file), level = "debug", fields(config_file = %config_file.display()))]
pub fn write_io_config(
    config_file: &Path,
    config: &mut ConfigFile,
    override_file: bool,
) -> anyhow::Result<()> {
    let config_file_display = config_file.display();
    if config_file.exists() && !override_file {
        bail!(
            "Config file at {config_file_display} already exists, delete it before generating a new one or use -f to override"
        );
    }
    if let Some(parent) = config_file.parent() {
        create_dir_all(parent)
            .with_context(|| format!("Failed to create config dir at ({})", parent.display()))?;
    }
    let mut str = config
        .to_string_pretty()
        .with_context(|| format!("Failed to generate TOML config for ({config_file_display})"))?;
    if !str.starts_with(CONFIG_EXPLANATION) {
        str = format!("{CONFIG_EXPLANATION}{str}");
    }

    let mut file = File::create(config_file)
        .with_context(|| format!("Failed to create config file at ({config_file_display})"))?;
    file.write_all(str.as_bytes())
        .with_context(|| format!("Failed to write to config file at ({config_file_display})"))
        .inspect_err(|_| {
            info!("New config contents: {str:?}");
        })?;

    debug!("Config file written successfully at {config_file_display}");
    Ok(())
}
