use std::{
    fs::{File, create_dir_all},
    io::Write,
    path::Path,
};

use anyhow::{Context, bail};
use tracing::{debug, info, instrument};

use crate::workarrounds::io::WorkarroundsFile;

const CONFIG_EXPLANATION: &str = "# Generated by hyprshell\n";

/// needs a mutable ref because writing the config to file forces a sync of the struct values
/// into the backing toml edit Document which requires mutable ref
#[instrument(skip(workarrounds, workarrounds_file), level = "debug", fields(workarrounds_file = %workarrounds_file.display()))]
pub fn write_io_workarrounds(
    workarrounds_file: &Path,
    workarrounds: &mut WorkarroundsFile,
    override_file: bool,
) -> anyhow::Result<()> {
    let workarrounds_file_display = workarrounds_file.display();
    if workarrounds_file.exists() && !override_file {
        bail!("Workarround file at {workarrounds_file_display} already exists");
    }

    if let Some(parent) = workarrounds_file.parent() {
        create_dir_all(parent).with_context(|| {
            format!(
                "Failed to create workarrounds dir at ({})",
                parent.display()
            )
        })?;
    }
    let mut str = workarrounds.to_string_pretty().with_context(|| {
        format!("Failed to generate TOML workarrounds for ({workarrounds_file_display})")
    })?;
    if !str.starts_with(CONFIG_EXPLANATION) {
        str = format!("{CONFIG_EXPLANATION}{str}");
    }

    let mut file = File::create(workarrounds_file).with_context(|| {
        format!("Failed to create workarrounds file at ({workarrounds_file_display})")
    })?;
    file.write_all(str.as_bytes())
        .with_context(|| {
            format!("Failed to write to workarrounds file at ({workarrounds_file_display})")
        })
        .inspect_err(|_| {
            info!("New workarrounds contents: {str:?}");
        })?;

    debug!("Workarrounds file written successfully at {workarrounds_file_display}");
    Ok(())
}
