disable_toast = false
launcher = { enable = true, items = 5 }

[[keybinds]]
open = { modifier = "Super", key = "Super", must_hold_modifier = false }
navigate = { forward = "Tab", backwards = "Grave" }
close = { escape = true, close_on_reopen = true }


[[keybinds]]
open = { modifier = "Super", key = "Tab", must_hold_modifier = false }
navigate = { backwards = "Grave", arrow_keys = true }
close = { escape = true, close_on_reopen = true }

max_switch_offset = 5
hide_active_window_border = false
monitors = ["HDMI-0", "DP-1"]
show_workspaces_on_all_monitors = false


[[keybinds]]
open = { modifier = "Alt", key = "Tab", must_hold_modifier = true }
navigate = { backwards = "Grave", arrow_keys = false }
close = { escape = true, close_on_reopen = true }

max_switch_offset = 5
hide_active_window_border = false
monitors = ["HDMI-0", "DP-1"]
show_workspaces_on_all_monitors = false

# must_hold_modifier = true disallows launcher
# must_hold_modifier = true causes navigate.forward and navigate.backwards to be bound with open.modifier as mod
# must_hold_modifier = true disallows changing navigate.forward as open.mod + open.key and open.mod + navigate.backwards are bound
# navigate.forward is the same as open.key
# open.must_hold_modifier = true ignores close.close_on_reopen