use std::fmt::Debug;
use std::path::PathBuf;
use std::str::FromStr;

use clap::{Args, Parser, Subcommand, ValueEnum};
use clap::builder::ValueParser;
use serde::{Deserialize, Serialize};

#[derive(Parser, Debug, Clone)]
#[command(
    author,
    version,
    about,
    long_about = "A CLI/GUI that allows switching between windows in Hyprland\nvisit https://github.com/H3rmt/hyprswitch/blob/main/README.md to see example configs"
)]
pub struct App {
    #[clap(flatten)]
    pub global_opts: GlobalOpts,

    #[clap(subcommand)]
    pub command: Command,
}

#[derive(Subcommand, Debug, Clone)]
pub enum Command {
    /// Initialize and start the Daemon
    Init {
        /// Specify a path to custom css file
        #[arg(long)]
        custom_css: Option<PathBuf>,

        /// Show the window title in the GUI (fallback to class if title is empty)
        #[arg(long)]
        show_title: bool,
    },
    /// Used to send commands to the daemon (used in keymap that gets generated by gui)
    Dispatch {
        #[clap(flatten)]
        simple_opts: SimpleOpts,
    },
    /// Opens the GUI
    Gui {
        #[clap(flatten)]
        gui_config: GuiConf,

        #[clap(flatten)]
        config: SimpleConf,
    },
    /// Switch without using the GUI / Daemon (switches directly)
    Simple {
        #[clap(flatten)]
        simple_opts: SimpleOpts,

        #[clap(flatten)]
        simple_conf: SimpleConf,
    },
    /// Close the GUI, executes the command to switch window
    Close {
        /// Don't switch to the selected window, just close the GUI
        #[arg(long)]
        kill: bool,
    },
}


// ModKey doesnt work (if pressed to fast closes instantly)
#[derive(clap::ValueEnum, Clone, Default, Debug, Serialize, Deserialize)]
pub enum CloseType {
    #[default]
    /// Close when pressing the mod key + key again (e.g., SUPER + TAB) or an index key (1, 2, 3, ...) or clicking on a window in GUI (or pressing escape)
    ModKeyIndex,
    /// Close when pressing an index key (1, 2, 3, ...) or clicking on a window in GUI (or pressing escape)
    Index,
    /// Close when pressing the mod key + key again (e.g., SUPER + TAB) or clicking on a window in GUI (or pressing escape)
    ModKey,
    /// Close when releasing the mod key (e.g., SUPER) or clicking on a window in GUI (or pressing escape)
    ModKeyRelease,
    /// Close when clicking on a window in GUI (or pressing escape)
    None,
}

#[derive(Args, Debug, Clone)]
pub struct GuiConf {
    /// The modifier key to used to open the GUI
    #[arg(long)]
    pub mod_key: ModKey,

    /// The key to used to open the GUI (e.g., tab)
    #[arg(long)]
    pub key: String,

    /// How to close hyprswitch
    #[clap(long, default_value_t, value_enum)]
    pub close: CloseType,

    /// The maximum offset you can switch to with number keys and is shown in the GUI
    #[arg(long, default_value = "5")]
    pub max_switch_offset: u8,

    /// The key used for reverse switching. Format: reverse-key=mod=<MODIFIER> or reverse-key=key=<KEY> (e.g., --reverse-key=mod=shift, --reverse-key=key=grave)
    #[arg(long, value_parser = ValueParser::new(ReverseKey::from_str), default_value = "mod=shift")]
    pub reverse_key: ReverseKey,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ReverseKey {
    Mod(String),
    Key(String),
}

impl Default for ReverseKey {
    fn default() -> Self {
        ReverseKey::Mod("shift".to_string())
    }
}

impl FromStr for ReverseKey {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let parts: Vec<&str> = s.split('=').collect();
        if parts.len() != 2 {
            return Err(format!("Invalid format for reverse: {}", s));
        }
        match (parts[0], parts[1]) {
            ("mod", value) => Ok(ReverseKey::Mod(value.to_string())),
            ("key", value) => Ok(ReverseKey::Key(value.to_string())),
            _ => Err(format!("Invalid format for reverse: {}", s)),
        }
    }
}


#[derive(Args, Debug, Clone)]
pub struct GlobalOpts {
    /// Print the command that would be executed
    #[arg(short = 'd', long)]
    pub dry_run: bool,

    /// Increase the verbosity level (max: -vv)
    #[arg(short = 'v', action = clap::ArgAction::Count)]
    pub verbose: u8,
}


#[derive(Args, Debug, Clone)]
pub struct SimpleConf {
    /// Include special workspaces (e.g., scratchpad)
    #[arg(long)]
    pub include_special_workspaces: bool,

    /// Sort all windows on every monitor like one contiguous workspace
    #[arg(long)]
    pub ignore_workspaces: bool,

    /// Sort all windows on matching workspaces on monitors like one big monitor
    #[arg(long)]
    pub ignore_monitors: bool,

    /// Only show/switch between windows that have the same class/type as the currently focused window
    #[arg(short = 's', long)]
    pub filter_same_class: bool,

    /// Only show/switch between windows that are on the same workspace as the currently focused window
    #[arg(short = 'w', long)]
    pub filter_current_workspace: bool,

    /// Only show/switch between windows that are on the same monitor as the currently focused window
    #[arg(short = 'm', long)]
    pub filter_current_monitor: bool,

    /// Sort windows by most recently focused
    #[arg(long)]
    pub sort_recent: bool,

    // TODO make this enum (client, workspace, monitor)
    /// Switches to next / previous workspace instead of client
    #[arg(long)]
    pub switch_workspaces: bool,
}

#[derive(Args, Debug, Clone)]
pub struct SimpleOpts {
    /// Reverse the order of windows / switch backwards
    #[arg(short = 'r', long)]
    pub reverse: bool,

    /// Switch to a specific window offset (default 1)
    #[arg(short = 'o', long, default_value = "1")]
    pub offset: u8,
}

#[derive(ValueEnum, Clone, Debug, Default, Serialize, Deserialize)]
#[value(rename_all = "snake_case")]
pub enum ModKey {
    AltL,
    AltR,
    CtrlL,
    CtrlR,
    #[default]
    SuperL,
    SuperR,
}