name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.check_commit.outputs.should_publish }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check commit message
        id: check_commit
        run: |
          commit_msg=$(git log -1 --pretty=%B)
          if [[ $commit_msg =~ ^chore\(hyprshell.*\):\ release ]]; then
            echo "should_publish=true" >> "$GITHUB_OUTPUT"
          else
            echo "Error: Commit message must start with 'chore(hyprshell): release'"
            echo "should_publish=false" >> "$GITHUB_OUTPUT"
          fi

  publish:
    needs: check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/h3rmt/actions-image:latest
      options: --privileged
    if: needs.check.outputs.should_publish == 'true'
    steps:
      - run: rustup default stable
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Install gtk4-layer-shell
        run: ./scripts/ci/install-gtk4-layer-shell.sh
      - name: Install cargo-workspaces
        run: |
          mkdir -p "$HOME/.cargo/bin"
          cargo install cargo-workspaces
          cargo ws --version
      - name: Publish to crates.io
        run: |
          set -euxo pipefail
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git fetch --tags origin hyprshell-release
          git checkout ${{ github.ref }} -b hyprshell-release
          git log -1 --pretty=%B
          git push origin HEAD:hyprshell-release --force
          git switch hyprshell-release
          
          current_sha=$(git rev-parse HEAD)
          jq --arg sha "$current_sha" '.["last-release-sha"]=$sha' release-please-config.json > tmp.json
          mv tmp.json release-please-config.json
          git add release-please-config.json
          git commit -m "chore(release): update last-release-sha"
          git push origin hyprshell-release
          
          git tag --delete ${{ github.ref_name }}
          git push --delete origin ${{ github.ref_name }}
          
          version=$(echo ${{ github.ref_name }} | sed 's/v//')
          cargo ws publish custom "$version" -m "chore(release): bump versions to $version" --no-individual-tags --allow-branch hyprshell-release --exact --yes --force "hyprshell*" --token ${{ secrets.CRATES_TOKEN }}
          
          # push current branch to hyprshell branch (for development)
          git fetch origin hyprshell
          git push origin HEAD:hyprshell
          
          gh release edit ${{ github.ref_name }} --latest --draft=false --title "hyprshell ${{ github.ref_name }}"
          
          cargo run --package hyprshell-xtask -- release licenses -v -o ./THIRD_PARTY_NOTICES.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@da03e160361ce01bf087e790b6ffd196d7dccff7 # v4.1.3
        with:
          pkgname: hyprshell
          pkgbuild: ./packaging/pkgbuild/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update hyprshell AUR package
          updpkgsums: true
          ssh_keyscan_types: rsa,ecdsa,ed25519
      - name: Publish AUR slim package
        uses: KSXGitHub/github-actions-deploy-aur@da03e160361ce01bf087e790b6ffd196d7dccff7 # v4.1.3
        with:
          pkgname: hyprshell-slim
          pkgbuild: ./packaging/pkgbuild/PKGBUILD-slim
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update hyprshell-slim AUR package
          updpkgsums: true
          ssh_keyscan_types: rsa,ecdsa,ed25519
      - name: Build binary for x86_64-unknown-linux-gnu
        run: |
          version=$(echo ${{ github.ref_name }} | sed 's/v//')
          ./scripts/ci/build-x86.sh
          mv "/tmp/hyprshell-x86_64.tar.zst" "/tmp/hyprshell-$version-x86_64.tar.zst"
          gh release upload ${{ github.ref_name }} "/tmp/hyprshell-$version-x86_64.tar.zst"
          mv "/tmp/hyprshell-slim-x86_64.tar.zst" "/tmp/hyprshell-slim-$version-x86_64.tar.zst"
          gh release upload ${{ github.ref_name }} "/tmp/hyprshell-slim-$version-x86_64.tar.zst"
          cargo clean
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build binary for aarch64-unknown-linux-gnu
        run: |
          version=$(echo ${{ github.ref_name }} | sed 's/v//')
          ./scripts/ci/install-gtk4-layer-shell-aarch64.sh
          ./scripts/ci/build-aarch64.sh
          mv "/tmp/hyprshell-aarch64.tar.zst" "/tmp/hyprshell-$version-aarch64.tar.zst"
          gh release upload ${{ github.ref_name }} "/tmp/hyprshell-$version-aarch64.tar.zst"
          mv "/tmp/hyprshell-slim-aarch64.tar.zst" "/tmp/hyprshell-slim-$version-aarch64.tar.zst"
          gh release upload ${{ github.ref_name }} "/tmp/hyprshell-slim-$version-aarch64.tar.zst"
          cargo clean
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish AUR bin package
        uses: KSXGitHub/github-actions-deploy-aur@da03e160361ce01bf087e790b6ffd196d7dccff7 # v4.1.3
        with:
          pkgname: hyprshell-bin
          pkgbuild: ./packaging/pkgbuild/PKGBUILD-bin
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update hyprshell-bin AUR package
          updpkgsums: true
          ssh_keyscan_types: rsa,ecdsa,ed25519
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: hyprshell
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Run Nix Flake Build
        run: |
          nix build '.#packages.x86_64-linux.hyprshell' -L
          readlink ./result | cachix push hyprshell
          rm result
          nix build '.#packages.x86_64-linux.hyprshell-slim' -L
          readlink ./result | cachix push hyprshell
          rm result